
[variables]
NODE_ENV = "production"
VITE_APP_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "bun"]

[phases.install]
cmds = [
  "bun install",
  "bun run build"
]

[phases.start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"

[staticAssets]
outputDir = "dist"
