
[variables]
NODE_ENV = "production"
VITE_APP_ENV = "production"

[phases.setup]
nixPkgs = ["pkgs.nodejs_18", "pkgs.nodejs_18.npm", "pkgs.vite"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm run build"
]

[phases.start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"

[staticAssets]
outputDir = "dist"
