// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epwkfzfoeyhfpziwiojl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwd2tmemZvZXloZnB6aXdpb2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTQyMjAsImV4cCI6MjA2NTIzMDIyMH0.ffspz_b0XjHAL5QJt6RX3OGyfMsmuzjsr0jNrQALdzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);